#!/bin/sh

# Exit on any error
set -euo pipefail

if [[ -n "${SKIP_GIT_HOOKS-}" ]]; then exit 0; fi

npm run lint
node scripts/no-only-in-features.mjs test/**/*.feature
npm run prettier
# we need to build the project before running tsc,
# because node_modules/playwright-bdd can be removed after npm install
# todo: better solution?
npm run build
npm run tsc
npm run knip
npm run docs:validate

# dont run tests on pre-push as we run on pre-commit and on ci
# npm test



