/**
 * Runs Playwright for each dir in features/* and validates messages report.
 * Originally, directories inside ./features are from Cucumber Compatibility Kit (CCK):
 * https://github.com/cucumber/compatibility-kit/tree/main/devkit/samples
 * https://github.com/cucumber/compatibility-kit/blob/main/javascript/README.md
 * They contained .feature files, steps and golden messages.ndjson files.
 *
 * But now the approach is a bit different:
 * We still use CCk feature files, but golden messages.ndjson files are generated by cucumber-js.
 * It allows to match against real cucumber-js output.
 *
 * TODO: sync feature files and steps with CCK.
 *
 * Run single feature:
 * node test/reporter-cucumber-msg/run/run-pw.mjs minimal
 *
 * Generate expected report by Cucumber:
 * node test/reporter-cucumber-msg/run/run-c.mjs minimal
 *
 * Or to debug:
 * cd test/reporter-cucumber-msg
 * FEATURE_DIR=minimal npx playwright test
 */
import {
  test,
  TestDir,
  execPlaywrightTestInternal,
  DEFAULT_CMD,
  playwrightVersion,
  normalizeExecErrorMessage,
} from '../_helpers/index.mjs';
import { globSync } from 'tinyglobby';

const onlyFeatureDir = process.env.FEATURE_DIR;
const skipDirs = [
  // For skipped scenarios Playwright does not even run fixtures.
  // We can't align here with Cucumber.
  'skipped',
  'skipped/',
];

const testDir = new TestDir(import.meta);

test(testDir.name, async () => {
  const dirs = onlyFeatureDir ? [onlyFeatureDir] : readAllFeatureDirs();
  for (const dir of dirs) {
    await checkFeature(dir);
  }
});

/**
 * Checks feature.
 * featureDir - name of feature dir inside ./features,
 * e.g. 'minimal'
 */
async function checkFeature(featureDir) {
  try {
    execPlaywrightTestInternal(testDir.name, { env: { FEATURE_DIR: featureDir } });
  } catch (e) {
    // some features normally exit with error
    if (normalizeExecErrorMessage(e.message) !== `Command failed: ${DEFAULT_CMD}`) {
      throw e;
    }
  }

  assertMessagesReport(featureDir);
}

function assertMessagesReport(featureDir) {
  const expectedFile = getExpectedMessagesReportPath(featureDir);

  testDir.assertMessagesReport(
    `features/${featureDir}/actual-reports/messages.ndjson`,
    expectedFile,
    {
      // cucumber-js still generates messages report without these fields,
      // although they are added to @cucumber/messages
      // See: https://github.com/cucumber/messages/pull/102
      'testRunStarted.id': null,
      'testRunFinished.testRunStartedId': null,
      'testCase.testRunStartedId': null,
    },
  );
}

function getExpectedMessagesReportPath(featureDir) {
  if (featureDir === 'hooks') {
    // For 'hooks' we use our own golden file because playwright-bdd intentionally doesn't emit
    // TestRunHookStarted/TestRunHookFinished messages (before/after run hooks are included
    // as test case steps instead), whereas cucumber-js does emit them.
    return playwrightVersion >= '1.59'
      ? `features/${featureDir}/expected-reports/messages-own.ndjson`
      : `features/${featureDir}/expected-reports/messages-own-until-pw-1.59.ndjson`;
  }

  switch (featureDir) {
    case 'examples-tables':
    case 'stack-traces':
      return playwrightVersion >= '1.59'
        ? `features/${featureDir}/expected-reports/messages.ndjson`
        : `features/${featureDir}/expected-reports/messages-until-pw-1.59.ndjson`;
    case 'retry':
      return playwrightVersion >= '1.59'
        ? `features/${featureDir}/expected-reports/messages-from-pw-1.59.ndjson`
        : `features/${featureDir}/expected-reports/messages-until-pw-1.59.ndjson`;
  }

  return `features/${featureDir}/expected-reports/messages.ndjson`;
}

/**
 * Returns all feature dirs.
 */
function readAllFeatureDirs() {
  return globSync('**', {
    cwd: testDir.getAbsPath('features'),
    deep: 0,
    onlyDirectories: true,
    expandDirectories: false,
  })
    .filter((dir) => !skipDirs.includes(dir))
    .map((dir) => dir.replace(/\/$|\\$/, ''));
}
