#!/bin/sh

# Exit on any error
set -euo pipefail

if [[ -n "${SKIP_PRE_PUSH-}" ]]; then exit 0; fi

GIT_BRANCH=`git rev-parse --abbrev-ref HEAD`

npm run lint
npm run prettier

# skip tests for docs branch
if [ "$GIT_BRANCH" == "docs" ]; then exit 0; fi

npx cross-env FORBID_ONLY=1 npm test
